### ISSUE TITLE
Where is the dat/hash file? 

### ISSUE THREAD

**Issue by gmipf** [saramibreak/DiscImageCreator#110]
I have dumped a PS5 triple layer disc and it seems complete but there was no dat file generated at the end.

Version: 20220201T112553

Console out:

```
sudo ./DiscImageCreator_linux.out bd /dev/sr0 dumps/ps5_h2fwse_ppsa01521/dump.bin 1
AppVersion
        64 bit, AnsiBuild, 20220201T112553
/media/Daten/DiscImageCreator_linux/dumps/ps5_h2fwse_ppsa01521/ doesn't exist, so create.
CurrentDirectory
        /media/Daten/DiscImageCreator_linux
WorkingPath
         Argument: dumps/ps5_h2fwse_ppsa01521/dump.bin
         FullPath: /media/Daten/DiscImageCreator_linux/dumps/ps5_h2fwse_ppsa01521/dump.bin
            Drive: /
        Directory: media/Daten/DiscImageCreator_linux/dumps/ps5_h2fwse_ppsa01521/
         Filename: dump
        Extension: .bin
StartTime: 2022-02-18T18:18:00+0100
Set the drive speed: 4496KB/sec
          Block Size: 4096
       Flagment Size: 4096
       All Block Num: 3662104064
      Free Block Num: 310756627
 Available Block Num: 309814947
          I Node Num: 0
     Free I Node Num: 0
Available I Node Num: 0
      File System ID: 17735766084729673982
          Mount Flag: 4096
 Max Filename Length: 255
DiskSize of [/media/Daten/DiscImageCreator_linux/dumps/ps5_h2fwse_ppsa01521]
        Total: 14999978246144 bytes
         Used: 13727119101952 bytes
        --------------------------
        Space: 1272859144192 bytes
         => There is enough disk space for dumping
Reading DirectoryRecord    7/   7
LBA[32593120, 0x1f154e0]: [F:ReadDVD][L:331]
        Opcode: 0xa8
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-04 = ILLEGAL_REQUEST - OTHER
Creating iso(LBA) 32593120/48097536Read retry from 32593120
Retry OK of 32593120
Creating iso(LBA) 48097536/48097536
EndTime: 2022-02-18T21:13:58+0100
```

log: [ps5_h2fwse_ppsa01521.zip](https://github.com/saramibreak/DiscImageCreator/files/8100225/ps5_h2fwse_ppsa01521.zip)

**Comment by saramibreak** [comment]
Only bd? I tried dvd on ubuntu, the dat is generated. I can't test the bd because I don't have bd drive for ubuntu pc.

**Comment by gmipf** [comment]
DVD is working. I think I know where the problem is. DIC had to reread a sector on that Bluray and it stopped hashing at that point maybe?

**Comment by saramibreak** [comment]
> DIC had to reread a sector on that Bluray and it stopped hashing at that point maybe?

If it's true, I already fixed it.
http://forum.redump.org/post/99497/#p99497

**Comment by gmipf** [comment]
I can't test anymore. My drive has stopped working with triple layer discs. The last dump was already hard to dump.

**Comment by gmipf** [comment]
Again the same with latest version. This time a BD-25 with no read errors at all.

```
$ sudo ./DiscImageCreator_linux.out bd /dev/sr0 dumps/ps4_rl_cusa00284hits_2/dump.iso 0
[sudo] password for gmipf: 
AppVersion
        64 bit, AnsiBuild, 20220301T213949
/media/Daten/DiscImageCreator_linux/dumps/ps4_rl_cusa00284hits_2/ doesn't exist, so create.
CurrentDirectory
        /media/Daten/DiscImageCreator_linux
WorkingPath
         Argument: dumps/ps4_rl_cusa00284hits_2/dump.iso
         FullPath: /media/Daten/DiscImageCreator_linux/dumps/ps4_rl_cusa00284hits_2/dump.iso
            Drive: /
        Directory: media/Daten/DiscImageCreator_linux/dumps/ps4_rl_cusa00284hits_2/
         Filename: dump
        Extension: .iso
StartTime: 2022-03-04T17:38:11+0100
          Block Size: 4096
       Flagment Size: 4096
       All Block Num: 3662104064
      Free Block Num: 242120692
 Available Block Num: 241348188
          I Node Num: 0
     Free I Node Num: 0
Available I Node Num: 0
      File System ID: 17735766084729673982
          Mount Flag: 4096
 Max Filename Length: 255
DiskSize of [/media/Daten/DiscImageCreator_linux/dumps/ps4_rl_cusa00284hits_2]
        Total: 14999978246144 bytes
         Used: 14008251891712 bytes
        ---------------------------
        Space:   991726354432 bytes
         => There is enough disk space for dumping
Reading DirectoryRecord    7/   7
Creating iso(LBA)  4608192/ 4608192
EndTime: 2022-03-04T17:43:58+0100
```

**Comment by gmipf** [comment]
Still not dat file on Version 20220501T221948 with PS4 BD25.

[ps4_sndcf_cusa31513_nodat.zip](https://github.com/saramibreak/DiscImageCreator/files/8742453/ps4_sndcf_cusa31513_nodat.zip)

**Comment by gmipf** [comment]
Tested again on latest Linux build 20220909T232418 with a PS5 BD66 and PS4 BD25 and the dat file is now generated properly. The case can be closed as fixed.
