### ISSUE TITLE
Several Errors (Primarily "error can't be fixed" and LOGICAL BLOCK ADDRESS OUT OF RANGE)

### ISSUE THREAD

**Issue by oblivioncth** [saramibreak/DiscImageCreator#64]
Not sure if this is due to poor use of switches with this drive, but I'm trying to follow the setup required by BetaArchive.

The disc is a little worn but very clean.

**Game Info:**
Disney/Pixar's BUZZ LIGHTYEAR 2nd GRADE
Ring Serial - F3235
Mastering Code - F3235 + + A0592-01
Mastering SID Code - IFPI L028
Mould Code - IFPI 1081
System/Media Type: IBM PC Compatible / CD-ROM

**Drive Info:**
LG WH14NS40
Alt - HL-DT-ST-BD-RE_WH14NS40
Firmware - 1.01-N1A12A1-211304042325 (I can crossflash to Asus BW-16D1HT 3.02)

**DIC Info:**
- Attempted using DIC 20210301
- Attempted using DIC_test (Dated: ‎Wednesday, ‎February ‎17, ‎2021, ‏‎4:51:12 AM)
- Current Dir: C:\Users\Chris\Desktop\BA DIC
- DIC Dir: C:\Users\Chris\Desktop\BA DIC\DIC
- Command: **DIC\DiscImageCreator.exe cd F media_dic\Disc01\Disc01.bin 48 /c2 1000 /q /ns /s 2**

**Error 1** (I'm assuming this isn't actually an issue and just DIC hard coded to check for a file even if it didn't get generated earlier):

```
FINDSTR: Cannot open DIC\!exelist.txt
[F:ReadCDForCheckingExe][L:1743] GetLastError: 2, The system cannot find the file specified.

FINDSTR: Cannot open DIC\!exelist.txt
[F:ReadCDForCheckingExe][L:1743] GetLastError: 2, The system cannot find the file specified.

[F:ReadCDForCheckingExe][L:1803] GetLastError: 2, The system cannot find the file specified.

Failed to DeleteFile C:\Users\Chris\Desktop\BA DIC\!exelist.txt
```
**Error 2:**
Multiple instances of these errors at different LBAs even though I am not using a Plextor drive
```
 LBA[086622, 0x1525e] Detected C2 error "F0 F0 F0 00 00 00 0F 0F 0F"
This error can't be fixed by plextor drive. Needs to dump it by non-plextor drive and replace it
```

**Error 3:**
```
LBA[317877, 0x4d9b5]: [F:ProcessReadCD][L:323]
        Opcode: 0xbe
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
LBA[317877, 0x4d9b5]: [F:ProcessReadCD][L:318]
        Opcode: 0xbe
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
LBA[317878, 0x4d9b6]: [F:ProcessReadCD][L:323]
        Opcode: 0xbe
        ScsiStatus: 0x02 = CHECK_CONDITION
        SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
```

And finally at the end, **Error 4:**
```
Need to reread sector:  89949 rereading times:    1/1000
Done. See _c2Error.txt
Copying .scm to .img
Descrambling data sector of img: 317876/317876
Exec ""C:\Users\Chris\Desktop\BA DIC\DIC\EccEdc.exe" check "C:\Users\Chris\Desktop\BA DIC\media_dic\Disc01\Disc01.img""
FILE: C:\Users\Chris\Desktop\BA DIC\media_dic\Disc01\Disc01.img
Checking sectors: 317876/317876
[ERROR] Number of sector(s) where user data doesn't match the expected ECC/EDC: 2
Total errors: 2
```

Generated files, excluding binary and empty ones, attached:
[BUZZ Dump Attempt.zip](https://github.com/saramibreak/DiscImageCreator/files/6094788/BUZZ.Dump.Attempt.zip)

**Comment by saramibreak** [comment]
Uploaded test version. https://www.mediafire.com/file/eq80y20l9cwf48f/DiscImageCreator_test.7z/file

> Error 1 

Fixed.

> Error 2

This message is only displayed by plextor drive.

> Error 3

No problem if this message is displayed by your drive.

**Comment by oblivioncth** [comment]
> Error 1

Looks good
> Error 2

Not sure if I misunderstand what you're saying, but that's what's strange, I got several of those messages while performing this dump on my WH14NS40, it wasn't a separate attempt with a Plextor drive. Haven't owned one of those in over a decade sadly.

With the test build provided though I didn't get any
>Error 3

Ah, I just realized these were still present, but accounted for as they no longer caused execution to halt, when you accounted for my drives firmware in #59. So OK, no problem

I think the dump is good at this point as I believe that all of the errors were corrected or expected, though there were many more this time. Let me know what you think
```
Checking sectors: 317876/317876
[ERROR] Number of sector(s) where bad MSF: 14
[ERROR] Number of sector(s) where user data doesn't match the expected ECC/EDC: 31
[ERROR] Number of sector(s) where sync(0x00 - 0x0c) is invalid: 2
Total errors: 47
Total warnings: 0
```
[Take Two.zip](https://github.com/saramibreak/DiscImageCreator/files/6096524/Take.Two.zip)

**Comment by saramibreak** [comment]
Unfortunately, the disc condition is bad. I recommend it's resurfaced.

**Comment by oblivioncth** [comment]
Ah alright, wasn't sure if the error report at the end like that was just counts of times it had to be reread or counts where it couldn't be read even after retries.

This one isn't high priority for me so I'll resurface it eventually, more so glad that the issues it presented were useful for fixes.
